name: Build and Push

on: 
  # Triggers the workflow on push/pull request or when new release outs events but only for the main branch
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    container: docker:dind
    steps:
      - name: "Step 1: Checkout"
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chandankumar4/ubuntu:dind
      